# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self

stages:
- stage: deploy
  jobs:
  - job: 'Default'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - powershell: |
        $n = 'LoECDA'
        $e = "$(EMAIL)"
        $url = "$(REPO_URL)"
        $pwd = ConvertTo-SecureString "$(PKG_PAT)" -AsPlainText -for
        $creds = New-Object PSCredential($e, $pwd)
        if(-not (Get-PSRepository | ? Name -eq $n)) {
            Register-PSRepository -Cr $creds -N $n -So $url -I Trusted -verb
        }
      displayName: 'Register Private Repository'
