name: cicd
on: [push]
jobs:
  linux-phase:
    name: Build Linux
    runs-on: ubuntu-16.04
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Build module
      shell: pwsh
      run: ./Build-Module.ps1 -installDep -configuration Release
    - name: Run C# unit tests
      shell: pwsh
      run: dotnet test
    - name: Run PowerShell unit tests
      shell: pwsh
      run: |
        Import-Module .\dist\*.psd1
        # This loads [PesterConfiguration] into scope
        Import-Module Pester
        $pesterArgs = [PesterConfiguration]::Default
        $pesterArgs.Run.Exit = $true
        $pesterArgs.Run.Path = './Tests/function'
        $pesterArgs.Run.PassThru = $false
        $pesterArgs.Output.Verbosity = "Normal"
        $pesterArgs.TestResult.Enabled = $true
        $pesterArgs.TestResult.OutputPath = 'test-results.xml'

        Invoke-Pester -Configuration $pesterArgs